### ISSUE TITLE
Hacktoberfest: Face recognition demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-face-recognition#1]
This is the tracker for polishing the “face recognition” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [x]  Run the existing two demos and identify and document what exists and what is or isn’t working for the next task (claimed by @Mukilan-Krishnakumar)
    - https://github.com/weaviate/weaviate-examples/tree/main/face-recognition-app
    - https://github.com/weaviate/weaviate-examples/tree/main/attendance-system-example
- [x]  Fixes for any of the identified issues
- [ ]  Update README to include: (claimed by @Mukilan-Krishnakumar)
    - [x] Consolidate the two existing demos into one by combining README.md files 
    - [x] Short description
    - [x] used technology
        - [ ] used Weaviate modules/ML models
    - [ ] demo video or screenshots of demo usage
    - [ ] Prerequisites
    - [ ] Setup instructions
    - [x] Usage instructions
    - [x] Dataset license if applicable
- [ ] Possible improvements/enhancements
    - [ ] Add progress bar to import file
    - [ ] Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point)
    - [ ] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)
        - [ ] After Weaviate release 1.22: swap out preview image

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by Mukilan-Krishnakumar** [comment]
Hey @iamleonie, 
I would like to run the existing two demos and identify and document what exists and what is or isn’t working for the next task.

**Comment by iamleonie** [comment]
Sounds great @Mukilan-Krishnakumar!

**Comment by Mukilan-Krishnakumar** [comment]
Hey @iamleonie
I have consolidated the following observations and I require your counsel on proceeding further.

## Face-Recognition-App
The first demonstration is the [face-recognition-app](https://github.com/weaviate/weaviate-examples/tree/main/face-recognition-app)
It works perfectly as intended, I had no issue with spinning up the instance or running the demonstration. 

One suggestion would be to make the `README.md` more descriptive.

Right now, the README has instructions for starting and stopping the demo but provides no additional information on how the demo works. 

It is solving a complex problem by leveraging Weaviate and vector similarity, if I am the reader I would like to know that. 

Other than that, it was a wonderfully packaged demonstration. 

## Attendance-System-Example
The second demonstration is the [attendance-system-example](https://github.com/weaviate/weaviate-examples/tree/main/attendance-system-example)

A few documentation changes:
- The demo requires us to add “some” images for custom data, it could be a bit more clear with how much images. For the test cases, they have 7 images for each class. Having this concrete number reduces confusion.
- One of the instructions in the `README.md` is “4. Spin up your weaviate instance by using the docker-compose.yml file”. It would be much more convenient to have a little code snippet in place to help someone who is not that familiar with docker-compose, such as:
  `docker compose up -d`
- Having a simple environment setup code also be a bonus.

This demonstration also had few code issues and RunTime problems:
- NotADirectoryError:
  I am running this demo from a Mac machine. MacOS automatically creates a `.DS_Store` file whenever a folder is created. This files creates the aforementioned error in the Code. 
  
<img width="1440" alt="Screenshot 2023-10-17 at 5 44 29 AM" src="https://github.com/weaviate-tutorials/DEMO-face-recognition/assets/71809485/bbea4448-529a-4df5-95de-2a231c60e447">


- When I wanted to test this demo with a combined image of all the use cases, it ran into `cv2.error`. It looks like a path issue. 
<img width="1440" alt="Screenshot 2023-10-17 at 5 47 33 AM" src="https://github.com/weaviate-tutorials/DEMO-face-recognition/assets/71809485/0d13355f-dbda-46e2-9e96-e6dea18ba0f1">

- When I selected one of the training images for testing, I ran into `TypeError`. I tested with `3.jpg` in Ronaldo folder. 
  
<img width="1440" alt="Screenshot 2023-10-17 at 5 49 30 AM" src="https://github.com/weaviate-tutorials/DEMO-face-recognition/assets/71809485/c4c059c5-af7e-4cd6-b6ab-4f0d1c4991ff">


## Concluding Thoughts
Both of the demonstrations showcase image search using similarity. Combining them into one proper demonstration would make it easier for readers to understand. I specifically liked the first demonstration, adding more description to it seems to be my preference. Let me know what you think.

**Comment by iamleonie** [comment]
Hi @Mukilan-Krishnakumar,
Thank you for your detailed analysis. 
I have initiated the repo with the [face-recognition-app](https://github.com/weaviate/weaviate-examples/tree/main/face-recognition-app) as a starting point, as you suggested.

Would you like to make the edits to the README.md file you suggested?

Also, are there any aspects from the second demo that you think should be incorporated to the first demo?

**Comment by Mukilan-Krishnakumar** [comment]
Thanks @iamleonie 
Yes, I would like to make the edits to the `README.md`. I found the second demo to be much interesting from a reader's perspective. It addressed reasoning behind this solution such as "Why we need this?", "How does it actually solve the problem?" etc. I would like to incorporate this to the first demo.

**Comment by iamleonie** [comment]
Sounds great! Thank you so much @Mukilan-Krishnakumar. Looking forward to your PR.

**Comment by Mukilan-Krishnakumar** [comment]
Hey @iamleonie, 
The PR has been merged. What should I do next? 

P.S: The PR is not recognized in the Hactoberfest Website stating that the Repo is not participating in Hactoberfest. Can you look into this?

**Comment by iamleonie** [comment]
Hi @Mukilan-Krishnakumar, I apologize, I had forgotten to add the Hacktoberfest label to the repository. It's now fixed. Can you please have a look and see if your PR is now recognized?

**Comment by Mukilan-Krishnakumar** [comment]
Thanks @iamleonie 
It is recognized and now under 7-day review period.

**Comment by Mukilan-Krishnakumar** [comment]
> Hey @iamleonie, The PR has been merged. What should I do next?
> 
> P.S: The PR is not recognized in the Hactoberfest Website stating that the Repo is not participating in Hactoberfest. Can you look into this?

What's the next plan of action @iamleonie?

**Comment by iamleonie** [comment]
@Mukilan-Krishnakumar If you would like to make more contributions to the demo sprint, you can pick any of the projects, find the Hacktoberfest issue and select one of the open tasks.

**Comment by Mukilan-Krishnakumar** [comment]
Hi @iamleonie, I will stick to this repository. I would like to add Demo Video, Prerequisites and Setup Instructions. Description, Usage instructions, Dataset License and Used technology stack already exist. Completing this should essentially complete the README updates.

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.

**Comment by Mukilan-Krishnakumar** [comment]
Thanks @iamleonie for your constant support and guidance during the Contribution. Couldn't have done this without you. Thanks to you and the wonderful team at Weaviate!!
